server:
  port: 8086
spring:
  application:
    name: service-consumer
  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: wuzx.cool:30000
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719 # 该端口启动http server ,控制台定义的限流规则才能传递过来，如果端口被占用，会被依次+1

management:
  endpoints:
    web:
      exposure:
        include: "*"