server:
  port: 8086
spring:
  application:
    name: service-consumer

  cloud:
    nacos:
      discovery:
        server-addr: wuzx.cool:30000

management:
  endpoints:
    web:
      exposure:
        include: "*"